apiVersion: apps/v1
kind: Replicaset
metadata:
  name: httpd-replicaset
spec:
  template:
    metadata:
      name: httpd-pod
      lables:
        app:frontend
    spec:
      containers:
        - name: httpd
          image: httpd
  replicas: 3
  selector:
    matchlabels:
      app: frontend
      
