apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  volumes:
   - name: mypvc-volume
     persistentVolumeclaim:
       claimName: ebc-pvc # Reference the PVC created earlier
  containers:
   - name: mycontainer
     image: nginx # Replace with your container image
     volumeMounts:
      - mountPath: /var/www/html # Replace with your desire mount path
        name: mypvc-volume
