apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce:
  storageClassName: standard  #reference the storageClass
  resources:
    requests:
      storage: 2Gi
